# filename: app/services/payment_service.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import asyncio
import logging
import os
import time
from enum import Enum

import httpx


logger = logging.getLogger(__name__)

PAYMENT_SERVICE_URL = os.getenv(
    "PAYMENT_SERVICE_URL",
    "http://127.0.0.1:9000",
)


class PaymentGatewayError(Exception):
    """Raised when the payment gateway cannot complete a request."""


class PaymentUnavailableError(Exception):
    """Raised when the circuit breaker blocks the request."""


class CircuitState(str, Enum):
    """Possible circuit breaker states."""

    CLOSED = "closed"
    OPEN = "open"
    HALF_OPEN = "half_open"


class SimpleCircuitBreaker:
    """Small in-memory circuit breaker for the payment gateway."""

    def __init__(
        self,
        failure_threshold: int = 3,
        recovery_timeout: float = 10,
    ) -> None:
        self.failure_threshold = failure_threshold
        self.recovery_timeout = recovery_timeout
        self.failure_count = 0
        self.state = CircuitState.CLOSED
        self.opened_at: float | None = None

    def allow_request(self) -> bool:
        """Return False while the circuit is open and recovering."""
        if self.state != CircuitState.OPEN:
            return True

        if self.opened_at is None:
            return False

        elapsed = time.monotonic() - self.opened_at

        if elapsed >= self.recovery_timeout:
            self.state = CircuitState.HALF_OPEN
            return True

        return False

    def record_success(self) -> None:
        """Close the circuit after a successful gateway response."""
        self.failure_count = 0
        self.state = CircuitState.CLOSED
        self.opened_at = None

    def record_failure(self) -> None:
        """Open the circuit after repeated gateway failures."""
        self.failure_count += 1

        if self.failure_count >= self.failure_threshold:
            self.state = CircuitState.OPEN
            self.opened_at = time.monotonic()


payment_breaker = SimpleCircuitBreaker()


async def process_payment(
    amount_cents: int,
    currency: str,
    token: str,
) -> dict:
    """Call the mock payment gateway asynchronously with retries."""

    if not payment_breaker.allow_request():
        logger.warning("Payment circuit breaker is open")
        raise PaymentUnavailableError(
            "Payment service is temporarily unavailable"
        )

    payload = {
        "amount_cents": amount_cents,
        "currency": currency,
        "token": token,
    }

    for attempt in range(1, 4):
        try:
            async with httpx.AsyncClient(timeout=2.0) as client:
                response = await client.post(
                    f"{PAYMENT_SERVICE_URL}/charge",
                    json=payload,
                )

            response.raise_for_status()
            payment_result = response.json()

            payment_breaker.record_success()

            logger.info(
                "Payment gateway response received",
                extra={
                    "payment_status": payment_result.get("status"),
                    "attempt": attempt,
                },
            )

            return payment_result

        except httpx.HTTPStatusError as error:
            payment_breaker.record_failure()
            logger.exception("Payment gateway returned HTTP error")
            raise PaymentGatewayError(
                "Payment gateway returned an error"
            ) from error

        except httpx.RequestError as error:
            logger.warning(
                "Payment gateway request failed",
                extra={"attempt": attempt},
            )

            if attempt == 3:
                payment_breaker.record_failure()
                raise PaymentGatewayError(
                    "Payment gateway is unavailable"
                ) from error

            await asyncio.sleep(0.2 * attempt)

    raise PaymentGatewayError("Payment request could not be completed")
