# filename: tests/test_casbin_policy.py | Code Generated by Sidekick is for learning and experimentation purposes only.

from app.utils.casbin_authorization import enforcer


def test_admin_can_create_products() -> None:
    assert enforcer.enforce(
        "admin",
        "/products",
        "POST",
    ) is True


def test_customer_cannot_create_products() -> None:
    assert enforcer.enforce(
        "customer",
        "/products",
        "POST",
    ) is False


def test_customer_can_read_products() -> None:
    assert enforcer.enforce(
        "customer",
        "/products",
        "GET",
    ) is True


def test_support_can_view_all_orders() -> None:
    assert enforcer.enforce(
        "support",
        "/orders/admin/all",
        "GET",
    ) is True
