# filename: main.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

# FastAPI is the web framework used to build and run the API.
from fastapi import FastAPI

# Base holds the shared SQLAlchemy metadata (all ORM models register against it).
from app.db.base import Base

# engine is the configured database connection used to talk to Postgres.
from app.db.sessions import engine

from app.models import cart, category, order, product, user

# Import the route handlers for each resource area of the application.
from app.routers import user_router, cart_router, order_router, product_router

# load_dotenv reads key/value pairs from the .env file into environment variables.
from dotenv import load_dotenv

from app.routers.payment_router import router as payment_router

import logging
from pathlib import Path

from app.utils.request_logging import RequestLoggingMiddleware
from app.utils.error_handlers import register_exception_handlers
from app.routers.notification_router import router as notification_router
from fastapi.middleware.cors import CORSMiddleware

# NEW: helpers used to render /docs with our own contrast styling injected.
from fastapi.openapi.docs import get_swagger_ui_html
from fastapi.responses import HTMLResponse


# override=True makes .env values take precedence over any existing env vars.
load_dotenv(override=True)

# Create all database tables defined on the models if they don't already exist.
# Suitable for the prototype; use migrations for schema changes.
Base.metadata.create_all(bind=engine)

# Instantiate the FastAPI application with metadata shown in the auto-generated docs.
# docs_url=None disables the built-in Swagger page so we can serve our own styled one.
app = FastAPI(
    title="Online Shopping API",
    version="1.0.0",
    description="Backend API for the Online Shopping Application",
    docs_url=None,
)

register_exception_handlers(app)

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(
            LOG_DIR / "application.log",
            encoding="utf-8",
        ),
    ],
)

# Allowed origins for CORS.
# Both "localhost" and "127.0.0.1" must be listed separately for each port
# because browsers treat them as distinct origins even though they resolve
# to the same address. Added "http://localhost:5174" to fix the blocked
# preflight request coming from the Vite dev server on that port.
allowed_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",   # added for consistency with localhost:5173
    "http://localhost:5174",   # ← FIX: was missing, caused the CORS preflight failure
    "http://127.0.0.1:5174",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(RequestLoggingMiddleware)

# ---------------------------------------------------------------------------
# Swagger /docs contrast fix.
# The default Swagger UI renders many labels in pale gray that are hard to read
# on white. This <style> block darkens/recolors every faint element seen in the
# docs (links, descriptions, table headers, lock icons, "No parameters", etc.).
# ---------------------------------------------------------------------------
_DOCS_CONTRAST_CSS = """
<style>

/* Code Generated by Sidekick is for learning and experimentation purposes only. */

/* ===== HEADER / ROW ICONS (lock, arrow, copy) — force dark fill ===== */

/* Expand/collapse chevron ▾ on the right of every row */
.swagger-ui .opblock-summary-control svg,
.swagger-ui .opblock-summary .arrow,
.swagger-ui svg.arrow,
.swagger-ui .expand-operation svg,
.swagger-ui .opblock-control-arrow svg { fill: #0f172a !important; }

/* Section-level collapse arrows (Auth, Cart, Products headers) */
.swagger-ui .opblock-tag .expand-operation svg,
.swagger-ui .opblock-tag svg { fill: #0f172a !important; }

/* Padlock (authorized/locked) icon on each endpoint */
.swagger-ui .authorization__btn svg,
.swagger-ui .opblock-summary .authorization__btn svg { fill: #d97706 !important; }  /* amber lock */

/* Copy-to-clipboard / clipboard icon (the one in the PATCH row) */
.swagger-ui .copy-to-clipboard button,
.swagger-ui .copy-to-clipboard svg,
.swagger-ui button.copy-to-clipboard svg,
.swagger-ui .view-line-link.copy-to-clipboard svg { fill: #4338ca !important; }

/* Make sure icons never inherit white from the row background */
.swagger-ui .opblock-summary svg { fill: #0f172a !important; }

/* Title + top badges (1.0.0, OAS 3.1) and the /openapi.json link */
.swagger-ui .info .title { color:#0f172a !important; font-weight:800; }
.swagger-ui .info a { color:#4338ca !important; font-weight:600; }
.swagger-ui .info p, .swagger-ui .info li,
.swagger-ui .info .base-url { color:#1e293b !important; }

/* Section titles: Auth, Cart, Products, Orders, Payments, Notifications */
.swagger-ui .opblock-tag { color:#0f172a !important; font-weight:700; }
.swagger-ui .opblock-tag small { color:#475569 !important; }

/* Endpoint path + description ("Register User", "List Cart", etc.) */
.swagger-ui .opblock .opblock-summary-path { color:#0f172a !important; font-weight:700; }
.swagger-ui .opblock .opblock-summary-description { color:#1e293b !important; font-weight:500; }

/* Method labels: solid, white, bold */
.swagger-ui .opblock .opblock-summary-method {
  color:#ffffff !important; font-weight:700 !important; text-shadow:none !important; }

/* Stronger colored borders so pale boxes don't vanish on white */
.swagger-ui .opblock { border-width:2px !important; border-radius:8px !important; }
.swagger-ui .opblock.opblock-get    { border-color:#3b82f6 !important; }
.swagger-ui .opblock.opblock-post   { border-color:#16a34a !important; }
.swagger-ui .opblock.opblock-put    { border-color:#d97706 !important; }
.swagger-ui .opblock.opblock-patch  { border-color:#0891b2 !important; }
.swagger-ui .opblock.opblock-delete { border-color:#dc2626 !important; }

/* Lock icons + expand arrows (were nearly invisible) */
.swagger-ui .opblock-summary .arrow, .swagger-ui svg.arrow { fill:#334155 !important; }
.swagger-ui .authorization__btn svg { fill:#d97706 !important; }

/* Authorize + Try it out buttons */
.swagger-ui .btn.authorize,
.swagger-ui .btn.try-out__btn { color:#4338ca !important; border-color:#4338ca !important; font-weight:600; }
.swagger-ui .btn.authorize svg { fill:#4338ca !important; }

/* Parameters / Responses tabs + section headers */
.swagger-ui .tab li, .swagger-ui .opblock-title,
.swagger-ui .opblock-section-header h4 { color:#0f172a !important; }
.swagger-ui .opblock-section-header { background:#f1f5f9 !important; }

/* The faint "Code / Description / Links" table headers + rows */
.swagger-ui table thead tr th, .swagger-ui table thead tr td,
.swagger-ui .response-col_status, .swagger-ui .response-col_description,
.swagger-ui .parameter__name, .swagger-ui .parameter__type,
.swagger-ui .col_header { color:#0f172a !important; font-weight:600; }
.swagger-ui .response-col_links { color:#475569 !important; }

/* "No parameters", "Controls Accept header", media-type labels */
.swagger-ui .opblock-description-wrapper p,
.swagger-ui .opblock-external-docs-wrapper p,
.swagger-ui .parameter__in, .swagger-ui .response-content-type { color:#334155 !important; }

/* JSON example box: light text on the dark box for readability */
.swagger-ui .highlight-code, .swagger-ui .microlight { background:#1e293b !important; }
.swagger-ui .microlight code, .swagger-ui .highlight-code * { color:#e2e8f0 !important; }
</style>
"""


@app.get("/docs", include_in_schema=False)
async def custom_swagger_ui():
    """Render the standard Swagger UI with our contrast stylesheet injected."""
    html = get_swagger_ui_html(openapi_url=app.openapi_url, title=app.title)
    body = html.body.decode().replace("</head>", _DOCS_CONTRAST_CSS + "</head>")
    return HTMLResponse(body)


# Register each router so its endpoints become part of the application.
app.include_router(user_router.router)       # User-related endpoints
app.include_router(cart_router.router)       # Shopping cart endpoints
app.include_router(product_router.router)    # Product catalog endpoints
app.include_router(order_router.router)      # Order management endpoints
app.include_router(payment_router)
app.include_router(notification_router)


# Health-check endpoint: a simple GET on "/" to confirm the API is up.
@app.get("/", tags=["Health"])
def root() -> dict[str, str]:
    # Return a basic JSON status message.
    return {"message": "Online Shopping API is running"}
