# filename: category.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

# Imports SQLAlchemy column types.
from sqlalchemy import Integer, String

# Imports SQLAlchemy ORM mapping and relationship helpers.
from sqlalchemy.orm import Mapped, mapped_column, relationship

# Imports the application's declarative base class.
from app.db.base import Base


# Represents a product category.
class Category(Base):

    # Maps the model to the categories table.
    __tablename__ = "categories"

    # Defines the category's primary key.
    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    # Defines a required, unique category name.
    name: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True,
    )

    # Defines an optional category description.
    description: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # Defines the one-to-many relationship with products.
    products: Mapped[list["Product"]] = relationship(
        back_populates="category",
    )

    # Returns a readable representation of the category.
    def __repr__(self) -> str:

        # Includes the category ID and name.
        return f"<Category id={self.id} name={self.name!r}>"
